repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v2.3.1'
    hooks:
    - id: pylint
      args: [
          --disable, invalid-name,
          --disable, unidiomatic-typecheck,
          --disable, bad-continuation,
          --disable, missing-docstring,
          --disable, import-error,
          --disable, duplicate-code,
          --disable, consider-using-ternary,
          --disable, line-too-long,
      ]
